services:
  - type: web
    name: orderkaaro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
